In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
a=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/classification_train.csv')
b=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/classification_test.csv')

train=np.array(a)
m,n=train.shape
test=np.array(b)
d_train=train[:].T
X_train=d_train[2:]
Y_train=d_train[1:2]
X_train=X_train/255

In [ ]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2







def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):

    A = np.exp(Z) / sum(np.exp(Z))
    return A
    


def ReLU_deriv(Z):
    return Z > 0




def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y





In [ ]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

In [ ]:
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)



    dZ2 = A2 - one_hot_Y


    dW2 = 1 / m * dZ2.dot(A1.T)


    db2 = 1 / m * np.sum(dZ2)


    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    
    dW1 = 1 / m * dZ1.dot(X.T)


    db1 = 1 / m * np.sum(dZ1)


    return dW1, db1, dW2, db2

In [ ]:
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [ ]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 1000 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 100000)

Iteration:  0
[4 4 1 ... 4 1 1] [[8 4 1 ... 9 4 6]]
0.11946666666666667
Iteration:  1000
[7 6 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.7812666666666667
Iteration:  2000
[7 6 1 ... 9 3 0] [[8 4 1 ... 9 4 6]]
0.8137666666666666
Iteration:  3000
[7 6 1 ... 9 3 0] [[8 4 1 ... 9 4 6]]
0.8279666666666666
Iteration:  4000
[7 6 1 ... 9 3 0] [[8 4 1 ... 9 4 6]]
0.8367333333333333
Iteration:  5000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8421
Iteration:  6000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.847
Iteration:  7000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8510666666666666
Iteration:  8000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8541333333333333
Iteration:  9000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8572666666666666
Iteration:  10000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8598333333333333
Iteration:  11000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8624666666666667
Iteration:  12000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8649
Iteration:  13000
[7 4 1 ... 9 2 0] [[8 4 1 ... 9 4 6]]
0.8670666666666667